apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
spec:
  replicas: 5 #bikin lima biar mantab.
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-container
          image: pingpongapp:latest #image dari yang telah dibuat
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
