kind: Service
apiVersion: v1
metadata:
  name: pingpong-service
spec:
  type: NodePort
  selector:
    app: pingpong-app
  ports:
    - protocol: TCP
      port: 80 # port internal host IP
      targetPort: 3000 # port aplikasi di container
      nodePort: 30007 # port untuk IP eksternal
    externalIPs:
    - 18.141.217.10
    
